version: "3"
services:

  neo4j:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "7474:7474"
      - "7687:7687"
      - "5005:5005"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,tnt.*
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_AUTH=neo4j/test
      - NEO4J_server_jvm_additional=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005